source :rubygems
gem 'data_mapper'
gem 'dm-core'
gem 'dm-sqlite-adapter'
gem 'dm-timestamps'
gem 'dm-validations'
gem 'dm-aggregates'
gem 'dm-migrations'
gem 'i18n'
gem 'daemons'
gem 'worker'
gem 'jabber-bot', :git => 'git@github.com:alx/jabber-bot.git'
gem 'capistrano'
